version: '3.8'
services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS---data-checksums}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD-}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=example123
      - POSTGRES_DB=${POSTGRES_DB:-$POSTGRES_USER}
      - TZ=${TZ:-UTC}
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U "${POSTGRES_USER:-postgres}"' ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgresnet
    restart: unless-stopped

networks:
  postgresnet:
    driver: bridge